In [1]:
import numpy as np
import pandas as pd

In [2]:
df_can = pd.read_excel("https://github.com/ardhiraka/PFDS_sources/blob/master/Canada.xlsx?raw=true",
             sheet_name='Canada by Citizenship',
              skiprows=range(20),
              skipfooter=2
             )

In [3]:
df_can.head(20)

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2012,2013,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2635,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,620,603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3774,4331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Immigrants,Foreigners,Angola,903,Africa,911,Middle Africa,902,Developing regions,1,...,70,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Immigrants,Foreigners,Antigua and Barbuda,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,0,...,51,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Immigrants,Foreigners,Argentina,904,Latin America and the Caribbean,931,South America,902,Developing regions,368,...,263,282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Immigrants,Foreigners,Armenia,935,Asia,922,Western Asia,902,Developing regions,0,...,258,207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Immigrants,Foreigners,Australia,909,Oceania,927,Australia and New Zealand,901,Developed regions,702,...,982,1121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Immigrants,Foreigners,Austria,908,Europe,926,Western Europe,901,Developed regions,234,...,102,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Immigrants,Foreigners,Azerbaijan,935,Asia,922,Western Asia,902,Developing regions,0,...,161,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Immigrants,Foreigners,Bahamas,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,26,...,60,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Immigrants,Foreigners,Bahrain,935,Asia,922,Western Asia,902,Developing regions,0,...,39,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Immigrants,Foreigners,Bangladesh,935,Asia,5501,Southern Asia,902,Developing regions,83,...,2640,3789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Immigrants,Foreigners,Barbados,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,372,...,132,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Immigrants,Foreigners,Belarus,908,Europe,923,Eastern Europe,901,Developed regions,0,...,277,247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Immigrants,Foreigners,Belgium,908,Europe,926,Western Europe,901,Developed regions,511,...,402,379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Immigrants,Foreigners,Belize,904,Latin America and the Caribbean,916,Central America,902,Developing regions,16,...,34,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Immigrants,Foreigners,Benin,903,Africa,914,Western Africa,902,Developing regions,2,...,391,397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
years = list(map(str, range(1980,2014)))
years

['1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [12]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [13]:
haiti = df_can.loc['Haiti', years]
haiti.head()

KeyError: 'Haiti'